micronaut:
  application:
    name: offers
  server:
    port: -1
redis:
  uri: "redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}"
consul:
  client:
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
endpoints:
  all:
    path: /actuator
    sensitive: false
offers:
  api:
    version: v1