version: '3'
services:
  prometheus:
    image: prom/prometheus    
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  nodeexporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
  cadvisor:
    image: google/cadvisor
    ports:
      - "8081:8080"
  grafana:
    image: grafana/grafana:6.3.5
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards/default/grafana-dashboard.json
   
  traefik:
    restart: always
    image: traefik:1.7
    container_name: traefik
    ports:
      - "80:80"
      - "8086:8080"    
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.127.0.0.1.xip.io"
      - "traefik.backend=traefik"      
      - "traefik.enable=true"
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro    

  neo4j:
    image: neo4j
    environment:
      NEO4J_AUTH: none
    ports:
      - 7687:7687
      - 7474:7474

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - 6379:6379

  consul:
    image: consul
    ports:
      - 8500:8500

  pets:
    image: kiwigrid/petstore-micronaut-prometheus-pets
    links:
      - mongodb
      - consul
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:pets.127.0.0.1.xip.io"
      - "traefik.backend=pets"
      - "traefik.enable=true"
    environment:
      MICRONAUT_SERVER_HOST: pets
      MICRONAUT_SERVER_PORT: 8080
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

  vendors:
    image: kiwigrid/petstore-micronaut-prometheus-vendors
    links:
      - consul
    environment:
      MICRONAUT_SERVER_HOST: vendors
      MICRONAUT_SERVER_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
  
  offers:
    image: kiwigrid/petstore-micronaut-prometheus-offers
    links:
      - storefront
      - redis
      - pets
      - consul
    environment:
      MICRONAUT_SERVER_HOST: offers
      MICRONAUT_SERVER_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      REDIS_HOST: redis
      REDIS_PORT: 6379
  
  comments:
    image: kiwigrid/petstore-micronaut-prometheus-comments
    links:
      - neo4j
      - consul
    environment:
      MICRONAUT_SERVER_HOST: comments
      MICRONAUT_SERVER_PORT: 8080
      NEO4J_HOST: neo4j
      NEO4J_PORT: 7687
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
  
  mail:
    image: kiwigrid/petstore-micronaut-prometheus-mail
    links:
      - consul
    environment:
      MICRONAUT_SERVER_HOST: mail
      MICRONAUT_SERVER_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
  
  storefront:
    image: kiwigrid/petstore-micronaut-prometheus-storefront
    ports:
      - "8080:8080"
    links:
      - pets
      - vendors
      - comments
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:storefront.127.0.0.1.xip.io"
      - "traefik.backend=storefront"
      - "traefik.enable=true"
    environment:
      MICRONAUT_SERVER_HOST: storefront
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
  
  frontend:
    image: kiwigrid/petstore-micronaut-prometheus-frontend
    links:
      - storefront
    ports:
      - 3000:3000
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:frontend.127.0.0.1.xip.io"
      - "traefik.backend=frontend"
      - "traefik.enable=true"
    volumes:
      - ./petstore/frontend/react/src:/usr/src/app/src
      - ./petstore/frontend/react/public:/usr/src/app/public
