version: '3'
services:
  prometheus:
    image: prom/prometheus    
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml

  nodeexporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
  cadvisor:
    image: google/cadvisor
    ports:
      - "8081:8080"
  grafana:
    image: grafana/grafana:6.3.5
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
       