apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
  access: proxy
  orgId: 1
  url: "http://prometheus:9090"
  basicAuth: false
  isDefault: true
  jsonData: {}
  version: 1
  editable: true
