{
 "title": "Micronaut Services",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend!=\"\"}[1m])) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(traefik_backend_request_duration_seconds_sum{backend!=\"\", backend!~\"grafana.*\"}[1m])) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(traefik_backend_requests_total{backend!=\"\", code=~\"5..\"}[1m])) by (backend)) or vector(0)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Error Log Events Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(logback_events_total{level=\"error\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}