logLevel = "DEBUG"
debug = true
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
  [entryPoints.http]
    address = ":80"

[api]
entrypoint="dashboard"

#Define Docker Backend Configuration
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
swarmMode = false
exposedbydefault = false

# Metrics definition
[metrics]
  [metrics.prometheus]
    entryPoint = "dashboard"
    buckets = [0.1,0.3,1.2,5.0]